services:

  ##################
  #### postgres ####
  ##################
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    networks:
        - ory-bridge
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: Kennwort1
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  postgres:
    build:
      context: ./postgres-db/
      dockerfile: Dockerfile
    container_name: postgres
    restart: always
    networks:
        - ory-bridge
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Kennwort1

      HYDRA_USER: hydra
      HYDRA_PASS: Kennwort1
      HYDRA_DB: hydra

      KRATOS_USER: kratos
      KRATOS_PASS: Kennwort1
      KRATOS_DB: kratos
    volumes:
      - hydra-data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  ory-hydra-db-migration:
    image: oryd/hydra:v1.10.6
    depends_on:
      - postgres
    command: migrate sql --yes ${HYDRA_DSN}
    networks:
      - ory-bridge

  ory-hydra:
    image: oryd/hydra:v1.10.6
    command: serve all
    networks:
      - ory-bridge
    ports:
      - "5444:4444"
      - "5445:4445"
    environment:
      SECRETS_SYSTEM: ${HYDRA_SYSTEM_SECRET}
      DSN: ${HYDRA_DSN}
      URLS_SELF_ISSUER: https://localhost:5444/
      URLS_CONSENT: http://localhost:9020/consent
      URLS_LOGIN: http://localhost:9020/login

  ory-kratos:
    image: oryd/kratos:v25.4.0
    command: serve all --config /config/kratos/config.yaml
    networks:
      - ory-bridge
    environment:
      DSN: ${KRATOS_DSN}
      SECRETS_DEFAULT: ${KRATOS_SYSTEM_SECRET}
    volumes:
      - ./kratos-config:/config/kratos

volumes:
  pgadmin-data:
  hydra-data:
  kratos_data:

networks:
  ory-bridge:
    driver: bridge
